FROM openjdk:17-jdk-slim AS BUILDER

COPY ./gazon-service/target/gazon-service.jar gazon-service.jar

FROM eclipse-temurin:17-jre-alpine
ENV JAVA_TOOL_OPTIONS -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
COPY --from=BUILDER gazon-service.jar gazon-service.jar
EXPOSE 8080
EXPOSE 5005
ENTRYPOINT ["java", "-Xmx512m", "-Xms256m", "-jar", "gazon-service.jar", "java $JAVA_OPTS -jar /gazon-service.jar"]