FROM maven:3.8.3-eclipse-temurin-17 AS BUILD
COPY . /home
COPY pom.xml /home
RUN mvn -f /home/pom.xml clean package -DskipTests


FROM eclipse-temurin:17-jre-alpine
ENV JAVA_TOOL_OPTIONS -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
COPY --from=BUILD home/gazon-service/target/gazon-service.jar gazon-service.jar
EXPOSE 8080
EXPOSE 5005
ENTRYPOINT ["java", "-Xmx512m", "-Xms256m", "-jar", "gazon-service.jar", "java $JAVA_OPTS -jar /gazon-service.jar"]