INSERT INTO example (example_text)
VALUES ('example text 1');
INSERT INTO example (example_text)
VALUES ('example text 2');
INSERT INTO example (example_text)
VALUES ('example text 3');
INSERT INTO example (example_text)
VALUES ('example text 4');
INSERT INTO example (example_text)
VALUES ('example text 5');